site_name: KelvinJoson.com
site_url: https://kelvinjoson.com
repo_url: https://github.com/KelvinJoson/kelvinjoson
repo_name: KelvinJoson/kelvinjoson
site_author: Kelvin Joson
copyright: Copyright &copy; 2022 Kelvin Joson
theme:
  font: false
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/github
    edit: material/file-document-edit
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.integrate

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to Dark Mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KelvinJoson
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kelvinjoson/
  analytics:
    provider: google
    property: G-6P3SJ6MH9Y
  consent:
    title: Cookie consent
    description: >-
      I use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of my home page and whether vistors
      find what they're searching for. With your consent, you're helping me to
      make this site better.
markdown_extensions:
  - admonition
  - nl2br
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: ⚑
      baselevel: 1

plugins:
  - search
  - roamlinks
  - callouts
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
