site_name: KELVINJOSON.COM
site_url: https://kelvinjoson.com/
#repo_url: https://github.com/KelvinJoson/kelvinjoson.com
#repo_name: KelvinJoson/kelvinjoson.com
site_author: Kelvin Joson
copyright: >
  Copyright &copy; 2022-2025 Kelvin Joson
  </br>
  <a href="#__consent">Change cookie settings</a>

theme:
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  name: material
  custom_dir: overrides
  icon:
    logo: material/alpha-k-box
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - announce.dismiss
    - navigation.tabs
    #- navigation.tabs.sticky
    - header.autohide
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.prune
    #- navigation.expand
    - search.share
    - search.suggest
    - navigation.indexes
    #- navigation.sections
    - toc.follow
    - toc.integrate
    - navigation.footer

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-5
        name: Switch to Dark Mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:kelvin@kelvinjoson.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kelvinjoson/
    - icon: fontawesome/brands/github
      link: https://github.com/KelvinJoson
    - icon: fontawesome/solid/earth-asia
      link: https://kelvinjoson.com

  analytics:
    provider: google
    property: G-6P3SJ6MH9Y
  consent:
    title: Cookie consent
    description: >-
      In order to monitor how well my home page is doing and whether visitors find what they are searching for, 
      I use cookies to keep track of your preferences and repeat visits.
      With your consent, you are assisting in improving this website.
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: ⚑
      baselevel: 1

plugins:
  - search
  - callouts
  - roamlinks
  - social:
      enabled: !ENV [CI, false]
      cards_layout_options:
        font_family: IBM Plex Sans
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
#nav:
#  - Home: index.md
#  - Projects:
#    - projects/index.md
#    - Project 1: projects/project_1.md